### ISSUE TITLE
Criar o Design System

### ISSUE THREAD

**Issue by gbrlCM** [Gui25Reis/Coverless#3]
## Todos
* Esboço do logo
* Palheta de cores
* Fontes, tamanho e uso
* Espaçamento
* Componentes básicos

**Comment by gbrlCM** [comment]
# Palheta de Cores
![ExcessivamenteShanty](https://user-images.githubusercontent.com/60374568/133157961-be073ae1-eaf9-406b-9f88-9c809ab2bc3d.png)

**Comment by biaduque** [comment]
![Moodboard](https://user-images.githubusercontent.com/53840501/133333986-a1d4cd22-74e3-4573-b3db-69335090ddfd.png)

**Comment by biaduque** [comment]
### Dicionário de Componentes (1.0 version)
![DicionarioComponentes](https://user-images.githubusercontent.com/53840501/133334251-91303ba5-73b8-46d3-a249-9b5ef9f1412e.png)

**Comment by biaduque** [comment]
### Atualização da moodboard com nova paleta de cores 
![Paleta de cores II](https://user-images.githubusercontent.com/53840501/134219593-49106d04-95e3-470b-866f-c4c17c6b2417.png)
