### ISSUE TITLE
Criar tela "Estante"

### ISSUE THREAD

**Issue by gbrlCM** [Gui25Reis/Coverless#6]
Tela tem todos os livros adicionados pelo usuário através do Descubra

* CollectionView e sua célula
![image](https://user-images.githubusercontent.com/60374568/132896095-69f2470f-993d-4091-8ecf-f2786e3ada1b.png)
* Tag de Estou Lendo, IMPLEMENTAÇÃO **OPCIONAL**
* Atalho favorito adiciona o livro aos favoritos e atualiza na base de dados
* Estrelas são apenas para visualização
* Quando não houver avaliação colocar uma mensagem ao invés das estrelas
* Capa do livro fica no quadrado
* Implementar um Empty State

## Elementos de acessibilidade:
* Voice Over

**Comment by Gui25Reis** [comment]
Feta e implementada
